import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const defaultHash = '$2b$10$wE99Jb0Z/T7Tq4xR7eY6euT3vE49mG09jO0N4uF7iA8a4m0vKxG7e'; // Password123!

async function main() {
  console.log('🚀 Memulai seeding Akun Admin PMB dan Data Pendaftar Database...');

  // 1. Akun Admin PMB Utama
  const adminPmb = await prisma.user.upsert({
    where: { email: 'admin.pmb@itn.ac.id' },
    update: {
      fullName: 'Bagus Wicaksono, S.Kom. (Panitia PMB)',
      role: 'ADMIN_PMB' as any,
      passwordHash: defaultHash,
      isActive: true,
    },
    create: {
      email: 'admin.pmb@itn.ac.id',
      fullName: 'Bagus Wicaksono, S.Kom. (Panitia PMB)',
      role: 'ADMIN_PMB' as any,
      passwordHash: defaultHash,
      isActive: true,
    },
  });

  // Alias pmb@itn.ac.id
  await prisma.user.upsert({
    where: { email: 'pmb@itn.ac.id' },
    update: {
      fullName: 'Panitia Penerimaan Mahasiswa Baru ITN',
      role: 'ADMIN_PMB' as any,
      passwordHash: defaultHash,
      isActive: true,
    },
    create: {
      email: 'pmb@itn.ac.id',
      fullName: 'Panitia Penerimaan Mahasiswa Baru ITN',
      role: 'ADMIN_PMB' as any,
      passwordHash: defaultHash,
      isActive: true,
    },
  });

  console.log('✅ Akun Admin PMB berhasil dibuat/diperbarui:', adminPmb.email);

  // 2. Data Pendaftar Nyata ke Database (admission_applicants)
  const initialApplicants = [
    {
      registrationNumber: 'PMB20270001',
      fullName: 'Aisyah Rahmadani',
      email: 'aisyah.pmb@gmail.com',
      phone: '081234567890',
      highSchool: 'SMAN 1 Teladan Jakarta',
      chosenStudyProgram: 'Teknik Informatika (S1)',
      jalurPendaftaran: 'Jalur Prestasi Akademik (Bebas Tes)',
      status: 'PASSED' as any,
      testScore: 88.5,
      birthDate: '2008-04-15',
      gender: 'Perempuan',
      address: 'Jl. Melati No. 12, Tebet, Jakarta Selatan',
      notes: 'Lolos jalur prestasi olimpiade sains bidang informatika tingkat provinsi.',
      verifiedAt: new Date('2026-08-10'),
      verifiedBy: 'Bagus Wicaksono, S.Kom.',
    },
    {
      registrationNumber: 'PMB20270002',
      fullName: 'Dimas Arya Prasetya',
      email: 'dimas.arya@yahoo.com',
      phone: '081399881122',
      highSchool: 'SMAN 8 Jakarta Selatan',
      chosenStudyProgram: 'Sistem Informasi (S1)',
      jalurPendaftaran: 'Jalur Nilai Rapor & Portofolio',
      status: 'VERIFIED' as any,
      testScore: 78.0,
      birthDate: '2008-07-22',
      gender: 'Laki-laki',
      address: 'Jl. Tebet Timur Dalam No. 45, Jakarta Selatan',
      notes: 'Berkas rapor lengkap rata-rata semester 1-5 adalah 86.4. Menunggu jadwal rapat yudisium.',
      verifiedAt: new Date('2026-08-12'),
      verifiedBy: 'Bagus Wicaksono, S.Kom.',
    },
    {
      registrationNumber: 'PMB20270003',
      fullName: 'Salsabila Putri Andini',
      email: 'salsabila.putri@gmail.com',
      phone: '082155443322',
      highSchool: 'SMA Taruna Nusantara',
      chosenStudyProgram: 'Teknik Mesin (S1)',
      jalurPendaftaran: 'Jalur Mandiri Online (CBT)',
      status: 'PENDING' as any,
      testScore: null,
      birthDate: '2008-09-10',
      gender: 'Perempuan',
      address: 'Jl. Merdeka No. 88, Magelang, Jawa Tengah',
      notes: 'Baru mendaftar dan mengunggah scan ijazah/SKL. Belum verifikasi berkas.',
      verifiedAt: null,
      verifiedBy: null,
    },
    {
      registrationNumber: 'PMB20270004',
      fullName: 'Kevin Jonathan Wijaya',
      email: 'kevin.jonathan@outlook.com',
      phone: '085711223344',
      highSchool: 'SMA Santa Ursula Jakarta',
      chosenStudyProgram: 'Teknik Informatika (S1)',
      jalurPendaftaran: 'Jalur Prestasi Akademik (Bebas Tes)',
      status: 'REGISTERED' as any,
      testScore: 92.0,
      birthDate: '2008-01-18',
      gender: 'Laki-laki',
      address: 'Jl. Boulevard Kelapa Gading Blok C-4, Jakarta Utara',
      notes: 'Telah melunasi UKT Gelombang 1 dan menyelesaikan verifikasi berkas fisik.',
      verifiedAt: new Date('2026-08-05'),
      verifiedBy: 'Bagus Wicaksono, S.Kom.',
    },
    {
      registrationNumber: 'PMB20270005',
      fullName: 'Nadya Aurelia Rahardjo',
      email: 'nadya.aurelia@gmail.com',
      phone: '081288776655',
      highSchool: 'SMAN 3 Bandung',
      chosenStudyProgram: 'Bisnis Digital (S1)',
      jalurPendaftaran: 'Jalur Nilai Rapor & Portofolio',
      status: 'PASSED' as any,
      testScore: 85.0,
      birthDate: '2008-11-03',
      gender: 'Perempuan',
      address: 'Jl. Dago Atas No. 102, Bandung',
      notes: 'Dinyatakan diterima. Menunggu pembayaran registrasi ulang sebelum 30 September 2026.',
      verifiedAt: new Date('2026-08-14'),
      verifiedBy: 'Bagus Wicaksono, S.Kom.',
    },
    {
      registrationNumber: 'PMB20270006',
      fullName: 'Rizky Ramadhan Saputra',
      email: 'rizky.saputra99@gmail.com',
      phone: '081977665544',
      highSchool: 'SMKN 1 Jakarta (Teknik Komputer)',
      chosenStudyProgram: 'Teknik Elektro (S1)',
      jalurPendaftaran: 'Jalur Mandiri Online (CBT)',
      status: 'FAILED' as any,
      testScore: 48.5,
      birthDate: '2007-12-25',
      gender: 'Laki-laki',
      address: 'Jl. Budi Utomo No. 7, Jakarta Pusat',
      notes: 'Nilai ujian CBT di bawah passing grade program studi (Passing grade: 65.00). Disarankan daftar Gelombang 2.',
      verifiedAt: new Date('2026-08-11'),
      verifiedBy: 'Bagus Wicaksono, S.Kom.',
    },
    {
      registrationNumber: 'PMB20270007',
      fullName: 'Fitri Handayani',
      email: 'fitri.handayani@gmail.com',
      phone: '087811992288',
      highSchool: 'MAN 2 Kota Bogor',
      chosenStudyProgram: 'Manajemen (S1)',
      jalurPendaftaran: 'KIP-K & Beasiswa Nusantara',
      status: 'PENDING' as any,
      testScore: null,
      birthDate: '2008-06-30',
      gender: 'Perempuan',
      address: 'Jl. Pajajaran No. 15, Bogor Timur',
      notes: 'Menunggu proses survey kelayakan penerima beasiswa KIP Kuliah dari tim BAAK PMB.',
      verifiedAt: null,
      verifiedBy: null,
    },
    {
      registrationNumber: 'PMB20270008',
      fullName: 'Farhan Pratama Putra',
      email: 'farhan.pratama@gmail.com',
      phone: '085233445566',
      highSchool: 'SMAN 28 Jakarta Selatan',
      chosenStudyProgram: 'Teknik Informatika (S1)',
      jalurPendaftaran: 'Jalur Mandiri Online (CBT)',
      status: 'VERIFIED' as any,
      testScore: 81.5,
      birthDate: '2008-03-08',
      gender: 'Laki-laki',
      address: 'Jl. Ragunan Raya No. 23, Pasar Minggu, Jakarta Selatan',
      notes: 'Ujian CBT selesai dengan skor 81.5. Berkas valid dan menunggu pleno penetapan.',
      verifiedAt: new Date('2026-08-15'),
      verifiedBy: 'Bagus Wicaksono, S.Kom.',
    },
    {
      registrationNumber: 'PMB20270009',
      fullName: 'Tiara Andini Kusuma',
      email: 'tiara.andini@gmail.com',
      phone: '081388990011',
      highSchool: 'SMA Labschool Kebayoran',
      chosenStudyProgram: 'Teknik Industri (S1)',
      jalurPendaftaran: 'Jalur Prestasi Akademik (Bebas Tes)',
      status: 'PASSED' as any,
      testScore: 90.0,
      birthDate: '2008-05-14',
      gender: 'Perempuan',
      address: 'Jl. Gandaria I No. 4, Kebayoran Baru, Jakarta Selatan',
      notes: 'Sertifikat pemenang lomba riset ilmiah remaja LIPI / BRIN terverifikasi valid.',
      verifiedAt: new Date('2026-08-08'),
      verifiedBy: 'Bagus Wicaksono, S.Kom.',
    },
    {
      registrationNumber: 'PMB20270010',
      fullName: 'Muhammad Ilham Fauzan',
      email: 'ilham.fauzan@gmail.com',
      phone: '081244332211',
      highSchool: 'SMAN 68 Jakarta Pusat',
      chosenStudyProgram: 'Sistem Informasi (S1)',
      jalurPendaftaran: 'Jalur Nilai Rapor & Portofolio',
      status: 'REGISTERED' as any,
      testScore: 87.0,
      birthDate: '2008-02-20',
      gender: 'Laki-laki',
      address: 'Jl. Salemba Raya No. 50, Jakarta Pusat',
      notes: 'Registrasi ulang tuntas. Nomor Induk Mahasiswa (NIM) telah diterbitkan sistem.',
      verifiedAt: new Date('2026-08-02'),
      verifiedBy: 'Bagus Wicaksono, S.Kom.',
    },
    {
      registrationNumber: 'PMB20270011',
      fullName: 'Bagas Aditya Nugroho',
      email: 'bagas.aditya@gmail.com',
      phone: '081722334455',
      highSchool: 'SMAN 1 Yogyakarta',
      chosenStudyProgram: 'Teknik Sipil (S1)',
      jalurPendaftaran: 'Jalur Mandiri Online (CBT)',
      status: 'PENDING' as any,
      testScore: null,
      birthDate: '2008-08-19',
      gender: 'Laki-laki',
      address: 'Jl. Malioboro No. 34, Yogyakarta',
      notes: 'Berkas KTP dan Kartu Keluarga belum terunggah dengan jelas.',
      verifiedAt: null,
      verifiedBy: null,
    },
    {
      registrationNumber: 'PMB20270012',
      fullName: 'Clara Shinta Dewi',
      email: 'clara.shinta@gmail.com',
      phone: '082266778899',
      highSchool: 'SMA Katolik Santo Paulus Surabaya',
      chosenStudyProgram: 'Akuntansi (S1)',
      jalurPendaftaran: 'Jalur Nilai Rapor & Portofolio',
      status: 'VERIFIED' as any,
      testScore: 79.5,
      birthDate: '2008-10-11',
      gender: 'Perempuan',
      address: 'Jl. Darmo No. 89, Surabaya',
      notes: 'Rapor semester 1-5 memenuhi kriteria minimal akuntansi (rata-rata 83.2).',
      verifiedAt: new Date('2026-08-16'),
      verifiedBy: 'Bagus Wicaksono, S.Kom.',
    },
  ];

  for (const app of initialApplicants) {
    await prisma.admissionApplicant.upsert({
      where: { registrationNumber: app.registrationNumber },
      update: {
        fullName: app.fullName,
        email: app.email,
        phone: app.phone,
        highSchool: app.highSchool,
        chosenStudyProgram: app.chosenStudyProgram,
        jalurPendaftaran: app.jalurPendaftaran,
        status: app.status,
        testScore: app.testScore,
        birthDate: app.birthDate,
        gender: app.gender,
        address: app.address,
        notes: app.notes,
        verifiedAt: app.verifiedAt,
        verifiedBy: app.verifiedBy,
      },
      create: {
        registrationNumber: app.registrationNumber,
        fullName: app.fullName,
        email: app.email,
        phone: app.phone,
        highSchool: app.highSchool,
        chosenStudyProgram: app.chosenStudyProgram,
        jalurPendaftaran: app.jalurPendaftaran,
        status: app.status,
        testScore: app.testScore,
        birthDate: app.birthDate,
        gender: app.gender,
        address: app.address,
        notes: app.notes,
        verifiedAt: app.verifiedAt,
        verifiedBy: app.verifiedBy,
      },
    });
  }

  const total = await prisma.admissionApplicant.count();
  console.log(`🎉 Berhasil memasukkan data pendaftar ke PostgreSQL database! Total pendaftar sekarang: ${total}`);
}

main()
  .catch((e) => {
    console.error('❌ Error saat seed data PMB:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
